[pytest]
addopts = --disable-warnings --pycodestyle --pydocstyle --isort --doctest-glob="*.rst" --doctest-modules --cov=invenio_previewer_mirador --cov-report=term-missing
testpaths = tests invenio_previewer_mirador
filterwarnings = 
    ignore::DeprecationWarning
    ignore::UserWarning 
